### ISSUE TITLE
Some screen display issues in Tsugaru when running Windows 95

### ISSUE THREAD

**Issue by OldMadMan** [captainys/TOWNSEMU#120]
First of all, thank you very much for your great work in making Tsugaru one of the very few FM TOWNS emulators capable of running Windows 95. I believe it will get better and better as time goes by.

After testing, I found that Tsugaru has some screen display problems when running Windows 95. I understand that these problems may be less important than other problems. I will only record them here and hope that they can be fixed in the future.

1.  There is a horizontal line in the lower center of the screen.
During the startup process of Windows 95, and after entering the system, a horizontal line visible to the naked eye can be found in the middle of the emulator's display screen. Below is the schematic.
![{980FFA54-25FF-4b98-A02E-026B203B81C5}](https://github.com/captainys/TOWNSEMU/assets/87818252/b498370d-a098-4ded-8c6d-a8cb233d9897)

2.  The emulator window does not expand when selecting a display resolution greater than 640 x 480. 
After I selected the screen resolution as 1024x768 in the system's display settings, the emulator window did not expand adaptively, resulting in a blurry screen. Users can indeed enlarge the window manually, but this will make it difficult to display point-to-point.Below is the schematic.
![{0B6246CC-A46A-4515-8724-4EFE283C7CAE}](https://github.com/captainys/TOWNSEMU/assets/87818252/d3dd39e9-2643-4ba6-b846-d4bd64805319)

**Comment by captainys** [comment]
Haha, you stepped on this :-)  The line is called a dumper-wire line.  It is emulating a signature shadow visible on Tri-Nitron monitors (like .  You can turn off Dumper Wire Line option to erase this line.

Regarding the screen resizing, you can specify scaling rate instead of auto scaling so that the emulator always keeps the window certain times the size of the VM resolution.  If you use auto scaling, VM will automatically adjust scaling to fit to the window size.

I have made some more changes to the CPU core.  Now it runs Puyopuyo 2 (you need to enable -HIGHRESPCM, install FM TOWNS WAVE driver from CD, and choose FM TOWNS WAVE driver as default play-back device, while keeping MIDI driver FM TOWNS Internal Sound).  Also I was able to play Xevious from Namco History Vol. 1.  It is not yet at really playable speed though.
