### ISSUE TITLE
Prince Of Persia Floppy Disk Copy Protection can't be past

### ISSUE THREAD

**Issue by BenoitAdam94** [captainys/TOWNSEMU#59]
So, I'm able to launch **Prince Of Persia** 1  on **Tsugaru FMTown Emulator** (24/09/2022) but I can't past the copy protection.

I have the floppy disk in *.bin format

> Mount FD0 before launching the game => Doesn't work
> Launch VM => FS0 => Select FD Image => Choose & Mount the floppy => Doesn't change a thing, still got the error message

![Tsugaru_GUI_h7PMVDNOl9](https://user-images.githubusercontent.com/45485644/199750918-90db4710-3b89-4ba1-ab8f-a7cb1c4b9aad.png)

**Comment by captainys** [comment]
Your screenshot is saying "Insert user disk in drive 0 and press enter."  Is it really a copy-protection?  Or is it waiting for a user disk?

Anyway, .BIN format does not replicate copy protection.  All known copy protections to date (known to me) for TOWNS can be replicated by .D77 format.  Please try to make .D77 format from __real disk__ and try again.  I suppose you understand it, but converting .BIN to .D77 doesn't help because .BIN already lost copy-protection information.

I'm going to talk about my copy-protection research in Demosplash in two weeks (https://www.demosplash.org/)  Please join us if you are interested.

**Comment by BenoitAdam94** [comment]
I think it's waiting for a user disk, but for me it seems like it's a copy-protection.

Same problem on Prince Of Persia 2

**Comment by BenoitAdam94** [comment]
I will check demosplash, do they upload broadcast on Youtube ?

**Comment by BenoitAdam94** [comment]
4D Sports Driving does ask for User Disk but it can be skipped.

![Tsugaru_GUI_4anGU2GMnh](https://user-images.githubusercontent.com/45485644/199774585-c60862d0-9d68-4e2f-a8c8-bbab60db81fc.png)

**Comment by BenoitAdam94** [comment]
Ok I'm getting it : 

I needed to create a new floppy disk trough "File" > "New" > 1232Kb Floppy Disk Image

Hell, not very simple to handle this emulator on first start... I'll write a guide and make a video on it probably because it's really hard for New Comers

One last question, can we change the defaut save folder for Profile/Floppy/savestates ? 

"C:\Users\Benoit\Documents\Tsugaru_TOWNS\" isn't convenient for me

Would be great to be able to choose 3 differents paths

**Comment by BenoitAdam94** [comment]
ok my guide is ready 


https://www.reddit.com/r/retrogaming/comments/ylxqys/fm_towns_emulator_tsugaru_startup_guide_tutorial/

**Comment by BenoitAdam94** [comment]
Ok I did a video tutorial

https://youtu.be/xZxWPcibcFU

**Comment by BenoitAdam94** [comment]
Closing the bug since it's resolved. Good luck for resolving bugs Captain !
